# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '启动器.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(424, 321)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 405, 290))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tom3 = QtWidgets.QCommandLinkButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.tom3.setFont(font)
        self.tom3.setObjectName("tom3")
        self.gridLayout.addWidget(self.tom3, 7, 1, 1, 1)
        self.tom4 = QtWidgets.QCommandLinkButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.tom4.setFont(font)
        self.tom4.setObjectName("tom4")
        self.gridLayout.addWidget(self.tom4, 7, 0, 1, 1)
        self.tom1 = QtWidgets.QCommandLinkButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.tom1.setFont(font)
        self.tom1.setObjectName("tom1")
        self.gridLayout.addWidget(self.tom1, 3, 0, 1, 1)
        self.tom2 = QtWidgets.QCommandLinkButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.tom2.setFont(font)
        self.tom2.setObjectName("tom2")
        self.gridLayout.addWidget(self.tom2, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.tom5 = QtWidgets.QCommandLinkButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.tom5.setFont(font)
        self.tom5.setObjectName("tom5")
        self.gridLayout.addWidget(self.tom5, 8, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.tom7 = QtWidgets.QCommandLinkButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.tom7.setFont(font)
        self.tom7.setObjectName("tom7")
        self.gridLayout.addWidget(self.tom7, 9, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.tom8 = QtWidgets.QCommandLinkButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.tom8.setFont(font)
        self.tom8.setObjectName("tom8")
        self.gridLayout.addWidget(self.tom8, 8, 1, 1, 1)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.commandLinkButton.setFont(font)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.gridLayout.addWidget(self.commandLinkButton, 9, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        m1 = self.tom1.clicked.connect(lambda: self.m1sp())
        m2 = self.tom2.clicked.connect(lambda: self.m2sp())
        m3 = self.tom3.clicked.connect(lambda: self.m3sp())
        m4 = self.tom4.clicked.connect(lambda: self.m4sp())
        m5 = self.tom5.clicked.connect(lambda: self.m5sp())
        m6 = self.tom8.clicked.connect(lambda: self.m6sp())
        m7 = self.tom7.clicked.connect(lambda: self.m7sp())
        about = self.commandLinkButton.clicked.connect(lambda: self.aboutsp())

        '''
        tom1:温度转换
        tom2:圆面积计算
        tom3:分数工具
        tom4:算式成立检测
        tom5:网站解析
        tom7:平年和闰年
        tom8:骰子
        '''

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "启动器"))
        self.tom3.setText(_translate("MainWindow", "分数工具"))
        self.tom4.setText(_translate("MainWindow", "算式成立检测"))
        self.tom1.setText(_translate("MainWindow", "温度转换"))
        self.tom2.setText(_translate("MainWindow", "圆面积计算"))
        self.label.setText(_translate("MainWindow", "欢迎使用"))
        self.tom5.setText(_translate("MainWindow", "骰子"))
        self.label_3.setText(_translate("MainWindow", "启动"))
        self.tom7.setText(_translate("MainWindow", "平年和闰年"))
        self.label_2.setText(_translate(
            "MainWindow", "欢迎使用百宝箱程序！这是百宝箱启动器，请点击以下按钮选择功能。"))
        self.tom8.setText(_translate("MainWindow", "网络解析"))
        self.commandLinkButton.setText(_translate("MainWindow", "关于"))

    def m1sp(self):
       import os
       os.popen('python m1p.py')

    def m2sp(self):
       import os
       os.popen('python m2p.py')

    def m3sp(self):
       import os
       os.popen('python m4p.py')

    def m4sp(self):
       import os
       os.popen('python m3p.py')

    def m5sp(self):
       import os
       os.popen('python m8p.py')

    def m6sp(self):
       import os
       os.popen('python m5p.py')

    def m7sp(self):
       import os
       os.popen('python m7p.py')

    def aboutsp(self):
       import os
       os.popen('python aboutp.py')
# try:

#         if __name__ == "__main__":
#             import sys
#             app = QtWidgets.QApplication(sys.argv)
#             widget = QtWidgets.QMainWindow()
#             ui = Ui_MainWindow()
#             ui.setupUi(widget)
#             widget.show()
#             sys.exit(app.exec_())


# except:
#     import errp
#     errp()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())